// <auto-generated />
using System;
using BOnlineHomeAssignement.Server.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BOnlineHomeAssignement.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260909193453_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppointmentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<Guid?>("EnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProviderId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ScheduledEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledStart")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SourceLeadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId")
                        .HasDatabaseName("IX_Appointment_EnrollmentId");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_Appointment_PatientId");

                    b.HasIndex("ScheduledStart")
                        .HasDatabaseName("IX_Appointment_ScheduledStart");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Appointment_Status");

                    b.HasIndex("TenantId", "EnrollmentId")
                        .HasDatabaseName("IX_Appointment_Tenant_Enrollment");

                    b.HasIndex("TenantId", "PatientId")
                        .HasDatabaseName("IX_Appointment_Tenant_Patient");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Changes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.BusinessRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid>("ProgramConfigurationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TriggerEvent")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProgramConfigurationId");

                    b.HasIndex("TenantId", "TriggerEvent", "IsActive")
                        .HasDatabaseName("IX_BusinessRule_Trigger");

                    b.ToTable("BusinessRules");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.CommunicationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("int");

                    b.Property<string>("MessageBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PatientPathwayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RelatedEntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ScheduledFor")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientPathwayId");

                    b.HasIndex("TenantId", "Channel")
                        .HasDatabaseName("IX_CommunicationMessage_Channel");

                    b.HasIndex("TenantId", "PatientPathwayId")
                        .HasDatabaseName("IX_CommunicationMessage_Pathway");

                    b.HasIndex("TenantId", "Status", "ScheduledFor")
                        .HasDatabaseName("IX_CommunicationMessage_Pending");

                    b.ToTable("CommunicationMessages");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.ContentTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ProgramConfigurationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Subject")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SupportedVariables")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProgramConfigurationId");

                    b.HasIndex("TenantId", "ProgramConfigurationId", "ContentType")
                        .HasDatabaseName("IX_ContentTemplate_Type");

                    b.ToTable("ContentTemplates");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProgramId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.FollowUpRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IntervalDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("FollowUpRules");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.FormDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApplicableStages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldsDefinition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("OnSubmitActions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("ProgramConfigurationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VisibilityConditions")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProgramConfigurationId");

                    b.HasIndex("TenantId", "ProgramConfigurationId")
                        .HasDatabaseName("IX_FormDef_Program");

                    b.ToTable("FormDefinitions");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("LeadSource")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Lead_Email");

                    b.HasIndex("TenantId", "Email")
                        .HasDatabaseName("IX_Lead_Tenant_Email");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedNurseId")
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("CareTeamIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("PrimaryDocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Patient_Email");

                    b.HasIndex("LastName", "FirstName")
                        .HasDatabaseName("IX_Patient_Name");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.PatientPathway", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CurrentProcessStageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EnteredStageAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastTransitionAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PathwayData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PatientType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ProgramConfigurationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StageDueAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransitionNotes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentProcessStageId");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProgramConfigurationId");

                    b.HasIndex("TenantId", "CurrentProcessStageId")
                        .HasDatabaseName("IX_PatientPathway_Stage");

                    b.HasIndex("TenantId", "EnrollmentId")
                        .HasDatabaseName("IX_PatientPathway_Enrollment");

                    b.HasIndex("TenantId", "PatientId")
                        .HasDatabaseName("IX_PatientPathway_Tenant_Patient");

                    b.ToTable("PatientPathways");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.ProcessStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AllowedStatuses")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AutoAdvanceConditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DurationDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("ProgramConfigurationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequiredFormIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleRequirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TriggeredTaskIds")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProgramConfigurationId");

                    b.HasIndex("TenantId", "ProgramConfigurationId", "Order")
                        .HasDatabaseName("IX_ProcessStage_Config_Order");

                    b.ToTable("ProcessStages");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.Program", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.ProgramConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultBusinessRules")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PatientTypes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkflowDefinition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkflowType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.HasIndex("TenantId", "ProgramId")
                        .HasDatabaseName("IX_ProgramConfig_Tenant_Program");

                    b.ToTable("ProgramConfigurations");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.Questionnaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldsDefinition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxSendCount")
                        .HasColumnType("int");

                    b.Property<Guid>("ProgramConfigurationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RecurrenceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RecurrenceValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TriggerEventType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProgramConfigurationId");

                    b.HasIndex("TenantId", "ProgramConfigurationId")
                        .HasDatabaseName("IX_Questionnaire_Program");

                    b.HasIndex("TenantId", "IsActive", "RecurrenceType")
                        .HasDatabaseName("IX_Questionnaire_Active_Recurrence");

                    b.ToTable("Questionnaires");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.QuestionnaireResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PatientPathwayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionnaireId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResponseData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PatientPathwayId");

                    b.HasIndex("QuestionnaireId");

                    b.HasIndex("TenantId", "PatientPathwayId")
                        .HasDatabaseName("IX_QuestionnaireResponse_Pathway");

                    b.HasIndex("TenantId", "QuestionnaireId", "Status")
                        .HasDatabaseName("IX_QuestionnaireResponse_Status");

                    b.ToTable("QuestionnaireResponses");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessibleStages")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AssignableTaskTypes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("CanApproveTransitions")
                        .HasColumnType("bit");

                    b.Property<bool>("CanOverrideRules")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewPathways")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Permissions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ProgramConfigurationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProgramConfigurationId");

                    b.HasIndex("TenantId", "RoleName")
                        .HasDatabaseName("IX_RolePermission_TenantRole");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.TaskDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignToRole")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("AutoEscalate")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ContentTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DueDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("OffsetDays")
                        .HasColumnType("int");

                    b.Property<Guid>("ProgramConfigurationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ContentTemplateId");

                    b.HasIndex("ProgramConfigurationId");

                    b.ToTable("TaskDefinitions");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompletionNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBySourceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreationSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Outcome")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("TaskDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("IX_TaskItem_DueDate");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("TaskDefinitionId");

                    b.HasIndex("TenantId", "AssignedTo")
                        .HasDatabaseName("IX_TaskItem_Assigned");

                    b.HasIndex("TenantId", "PatientId")
                        .HasDatabaseName("IX_TaskItem_Tenant_Patient");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_TaskItem_Status");

                    b.ToTable("TaskItems");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hostname")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Hostname")
                        .HasDatabaseName("IX_Tenant_Hostname");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.TenantConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique()
                        .HasDatabaseName("UX_TenantConfig_Tenant_Key");

                    b.ToTable("TenantConfigurations");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.TriggerExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeduplicationKey")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ExecutionResult")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PatientPathwayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TriggerConfigId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PatientPathwayId");

                    b.HasIndex("ScheduledAt")
                        .HasDatabaseName("IX_TriggerExecution_Scheduled");

                    b.HasIndex("TenantId", "DeduplicationKey")
                        .HasDatabaseName("IX_TriggerExecution_Dedup");

                    b.HasIndex("TenantId", "PatientPathwayId")
                        .HasDatabaseName("IX_TriggerExecution_Pathway");

                    b.HasIndex("TenantId", "Status", "NextRetryAt")
                        .HasDatabaseName("IX_TriggerExecution_Pending");

                    b.ToTable("TriggerExecutions");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.WorkflowEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventOccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PatientPathwayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TriggeredBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("VisibleToPatient")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientPathwayId");

                    b.HasIndex("TenantId", "EventOccurredAt")
                        .HasDatabaseName("IX_WorkflowEvent_Timeline");

                    b.HasIndex("TenantId", "PatientPathwayId")
                        .HasDatabaseName("IX_WorkflowEvent_Pathway");

                    b.HasIndex("TenantId", "EventType", "VisibleToPatient")
                        .HasDatabaseName("IX_WorkflowEvent_Type_Visibility");

                    b.ToTable("WorkflowEvents");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("BOnlineHomeAssignement.Server.Domain.Entities.Enrollment", "Enrollment")
                        .WithMany()
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BOnlineHomeAssignement.Server.Domain.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Enrollment");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.BusinessRule", b =>
                {
                    b.HasOne("BOnlineHomeAssignement.Server.Domain.Entities.ProgramConfiguration", "ProgramConfiguration")
                        .WithMany("BusinessRules")
                        .HasForeignKey("ProgramConfigurationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProgramConfiguration");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.CommunicationMessage", b =>
                {
                    b.HasOne("BOnlineHomeAssignement.Server.Domain.Entities.PatientPathway", "PatientPathway")
                        .WithMany()
                        .HasForeignKey("PatientPathwayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientPathway");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.ContentTemplate", b =>
                {
                    b.HasOne("BOnlineHomeAssignement.Server.Domain.Entities.ProgramConfiguration", "ProgramConfiguration")
                        .WithMany("ContentTemplates")
                        .HasForeignKey("ProgramConfigurationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProgramConfiguration");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("BOnlineHomeAssignement.Server.Domain.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BOnlineHomeAssignement.Server.Domain.Entities.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.FormDefinition", b =>
                {
                    b.HasOne("BOnlineHomeAssignement.Server.Domain.Entities.ProgramConfiguration", "ProgramConfiguration")
                        .WithMany("FormDefinitions")
                        .HasForeignKey("ProgramConfigurationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProgramConfiguration");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.PatientPathway", b =>
                {
                    b.HasOne("BOnlineHomeAssignement.Server.Domain.Entities.ProcessStage", "CurrentProcessStage")
                        .WithMany("PatientPathways")
                        .HasForeignKey("CurrentProcessStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BOnlineHomeAssignement.Server.Domain.Entities.Enrollment", "Enrollment")
                        .WithMany()
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BOnlineHomeAssignement.Server.Domain.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BOnlineHomeAssignement.Server.Domain.Entities.ProgramConfiguration", "ProgramConfiguration")
                        .WithMany("PatientPathways")
                        .HasForeignKey("ProgramConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentProcessStage");

                    b.Navigation("Enrollment");

                    b.Navigation("Patient");

                    b.Navigation("ProgramConfiguration");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.ProcessStage", b =>
                {
                    b.HasOne("BOnlineHomeAssignement.Server.Domain.Entities.ProgramConfiguration", "ProgramConfiguration")
                        .WithMany("ProcessStages")
                        .HasForeignKey("ProgramConfigurationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProgramConfiguration");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.ProgramConfiguration", b =>
                {
                    b.HasOne("BOnlineHomeAssignement.Server.Domain.Entities.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.Questionnaire", b =>
                {
                    b.HasOne("BOnlineHomeAssignement.Server.Domain.Entities.ProgramConfiguration", "ProgramConfiguration")
                        .WithMany()
                        .HasForeignKey("ProgramConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramConfiguration");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.QuestionnaireResponse", b =>
                {
                    b.HasOne("BOnlineHomeAssignement.Server.Domain.Entities.PatientPathway", "PatientPathway")
                        .WithMany()
                        .HasForeignKey("PatientPathwayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BOnlineHomeAssignement.Server.Domain.Entities.Questionnaire", "Questionnaire")
                        .WithMany("Responses")
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientPathway");

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("BOnlineHomeAssignement.Server.Domain.Entities.ProgramConfiguration", "ProgramConfiguration")
                        .WithMany()
                        .HasForeignKey("ProgramConfigurationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProgramConfiguration");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.TaskDefinition", b =>
                {
                    b.HasOne("BOnlineHomeAssignement.Server.Domain.Entities.ContentTemplate", "ContentTemplate")
                        .WithMany()
                        .HasForeignKey("ContentTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BOnlineHomeAssignement.Server.Domain.Entities.ProgramConfiguration", "ProgramConfiguration")
                        .WithMany("TaskDefinitions")
                        .HasForeignKey("ProgramConfigurationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ContentTemplate");

                    b.Navigation("ProgramConfiguration");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("BOnlineHomeAssignement.Server.Domain.Entities.Enrollment", "Enrollment")
                        .WithMany()
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BOnlineHomeAssignement.Server.Domain.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BOnlineHomeAssignement.Server.Domain.Entities.Program", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BOnlineHomeAssignement.Server.Domain.Entities.TaskDefinition", null)
                        .WithMany("CreatedTasks")
                        .HasForeignKey("TaskDefinitionId");

                    b.Navigation("Enrollment");

                    b.Navigation("Patient");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.TenantConfiguration", b =>
                {
                    b.HasOne("BOnlineHomeAssignement.Server.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.TriggerExecution", b =>
                {
                    b.HasOne("BOnlineHomeAssignement.Server.Domain.Entities.PatientPathway", "PatientPathway")
                        .WithMany()
                        .HasForeignKey("PatientPathwayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientPathway");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.WorkflowEvent", b =>
                {
                    b.HasOne("BOnlineHomeAssignement.Server.Domain.Entities.PatientPathway", "PatientPathway")
                        .WithMany()
                        .HasForeignKey("PatientPathwayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientPathway");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.ProcessStage", b =>
                {
                    b.Navigation("PatientPathways");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.ProgramConfiguration", b =>
                {
                    b.Navigation("BusinessRules");

                    b.Navigation("ContentTemplates");

                    b.Navigation("FormDefinitions");

                    b.Navigation("PatientPathways");

                    b.Navigation("ProcessStages");

                    b.Navigation("TaskDefinitions");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.Questionnaire", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("BOnlineHomeAssignement.Server.Domain.Entities.TaskDefinition", b =>
                {
                    b.Navigation("CreatedTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
